"""AETV (Autoencoder Television): analog video over HF OFDM."""

from .config import (
    AETV_MODES,
    AETV_MODES_BY_INDEX,
    RELEASE_MODES,
    RELEASE_MODE_LABELS,
    AETVBandGeometry,
    AETVModeSpec,
    BAND_N,
    BAND_U,
    BAND_W,
    BANDS,
    FS,
    RS,
    M,
    NCP,
    NSYM,
    SYMS_PER_FRAME,
    DATA_SYMS_PER_FRAME,
    FRAME_SAMPLES,
    FRAMES_PER_GOP,
    LATENTS_PER_GOP_N,
    LATENTS_PER_GOP_W,
    LATENTS_PER_GOP_U,
)
from .channel import AETVChannelConfig, AETVLatentChannel, AETVWaveformChannel
from .data import AETVOpenVidStreamDataset, AETVSyntheticVideoDataset
from .models import (
    AETVAutoencoder,
    AETVDecoder,
    AETVEncoder,
    ShallowVGGPerceptualLoss,
    SpatioTemporalDiscriminator3D,
    SpatioTemporalPatchGAN3D,
)
from .modem import (
    AETVDemodResult,
    StreamingDemodulator,
    demodulate_gop_stream,
    modulate_gop_chunks,
    modulate_gop_stream,
)
from .sync import Acquisition, SyncError, acquire

__all__ = [
    "AETV_MODES",
    "AETV_MODES_BY_INDEX",
    "RELEASE_MODES",
    "RELEASE_MODE_LABELS",
    "AETVBandGeometry",
    "AETVModeSpec",
    "BAND_N",
    "BAND_U",
    "BAND_W",
    "BANDS",
    "FS",
    "RS",
    "M",
    "NCP",
    "NSYM",
    "SYMS_PER_FRAME",
    "DATA_SYMS_PER_FRAME",
    "FRAME_SAMPLES",
    "FRAMES_PER_GOP",
    "LATENTS_PER_GOP_N",
    "LATENTS_PER_GOP_W",
    "LATENTS_PER_GOP_U",
    "AETVChannelConfig",
    "AETVLatentChannel",
    "AETVWaveformChannel",
    "AETVOpenVidStreamDataset",
    "AETVSyntheticVideoDataset",
    "AETVAutoencoder",
    "AETVEncoder",
    "AETVDecoder",
    "ShallowVGGPerceptualLoss",
    "SpatioTemporalDiscriminator3D",
    "SpatioTemporalPatchGAN3D",
    "AETVDemodResult",
    "modulate_gop_stream",
    "modulate_gop_chunks",
    "StreamingDemodulator",
    "demodulate_gop_stream",
    "Acquisition",
    "SyncError",
    "acquire",
]
